# Generated by Django 4.1.4 on 2022-12-10 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('firstName', models.CharField(max_length=200, null=True)),
                ('lastName', models.CharField(max_length=200, null=True)),
                ('age', models.IntegerField(null=True)),
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=500, null=True)),
                ('month_batches', models.CharField(default='000000', max_length=6, null=True)),
            ],
        ),
    ]
