# Generated by Django 4.1.4 on 2022-12-11 16:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='month_batches',
        ),
        migrations.AddField(
            model_name='user',
            name='lastPaid',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(11), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(65), django.core.validators.MinValueValidator(18)]),
        ),
    ]
